apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1 # może być tylko jedna replika, gdyż bazy danych pomiędzy podami nie będą się komunikowały, a baza musi przechowywać takie same wartości
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: normanmenescdv/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
