apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  connectionstring: U2VydmVyPWxvY2FsaG9zdFxUb0RvTGlzdDtEYXRhYmFzZT1Ub0RvTGlzdDtVc2VyIElkPWFwcDtQYXNzd29yZD0xTzUwM1NKZGJsRjE2ZVowdjVsbDs=
